# -*- coding: utf-8 -*-
"""ai_stats_tutor_llm_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E9yMOLDeYNh7OB3aDP5ELSdAifeBKiZS

# **STEP 1 — INSTALL**
"""

import torch
print(torch.cuda.is_available())

"""# **STEP 2 — IMPORT + MODEL LOAD**"""

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_name = "microsoft/Phi-3-mini-4k-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.float16
)

"""# **STEP 3 — FAST AI FUNCTION**"""

def ask_ai(query):

    prompt = f"""
You are a Statistics teacher.

Instruction:
- Understand the type of question first.
- If it is a definition question → explain simply.
- If it is a "when/which test" question → give conditions and rules.
- Stay strictly on topic.
- Always give a real-life example.
- Solve the problem step by step and give final answer.


Output format:
Answer the question clearly in simple words with one example.

Explain:
{query}
"""

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=256
    )

    outputs = model.generate(
        input_ids=inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        max_new_tokens=150,
        do_sample=False
    )

    return tokenizer.decode(outputs[0], skip_special_tokens=True)

"""# **STEP 4 — TEST IT**"""

print(ask_ai("when to use z test"))

print(ask_ai("difference between correlation and regresssion"))

ask_ai("what is the probability of getting two tails when a coin is tossed twice?")

ask_ai("calculate mean as n=12 and sum of X =500?")