# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17YkRW0EUWWXfxDIGlcOxOJw0gmTQUGn8
"""

import requests

API_URL = "https://szl04dhy37c0ic-8000.proxy.runpod.net/v1/chat/completions"

messages = [
    {
        "role": "system",
        "content": "You are a helpful statistics tutor. Give only final answers clearly."
    }
]

while True:
    user_input = input("You: ")

    if user_input.lower() in ["exit", "quit"]:
        break

    messages.append({"role": "user", "content": user_input})

    response = requests.post(
        API_URL,
        json={
            "model": "microsoft/Phi-3-mini-4k-instruct",
            "messages": messages
        }
    )

    result = response.json()

    # 🔥 ONLY AI ANSWER (clean output)
    answer = result["choices"][0]["message"]["content"]

    print("AI:", answer)

    messages.append({"role": "assistant", "content": answer})